### ISSUE TITLE
Add `mkdocs.yml` config file to template

### ISSUE THREAD

**Issue by joshuadavidthomas** [westerveltco/django-twc-project#203]
For our shared, central docs site.

Reference: https://github.com/westerveltco/cms/blob/29b91d55f9b5da7ab4533df6e64d4d239553946c/mkdocs.yml

**Comment by joshuadavidthomas** [comment]
```yaml
# src/django_twc_project/mkdocs.yml
site_name: {{ docs_site_name }}
repo_name: "{{ github_owner }}/{{ github_repo }}"
repo_url: "https://github.com/{{ github_owner }}/{{ github_repo }}"
docs_dir: "docs"

theme:
  name: material
  language: "en"

nav:
  - Home: "index.md"
  - Users: "applications/users/index.md"
  - Just: "just.md"
```

For lack of a better template variable, `docs_site_name` needs to be added to `copier.yml` at the base of the repo.
